<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-android36.0</TargetFramework>
    <SupportedOSPlatformVersion>24.0</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationId>vn.webnow.wnterm</ApplicationId>
    <ApplicationVersion>7</ApplicationVersion>
    <ApplicationDisplayVersion>1.4.2</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <RuntimeIdentifiers>android-arm64;android-x64</RuntimeIdentifiers>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AndroidEnableMarshalMethods>false</AndroidEnableMarshalMethods>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Android" Version="12.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WNTerm.App\WNTerm.App.csproj" />
  </ItemGroup>

</Project>
